### ISSUE TITLE
how do i compile hadesmem?

### ISSUE THREAD

**Issue by Dokman** [namreeb/dumpwow#1]
how i can do it? it's a reallyu odd compilation

**Comment by namreeb** [comment]
It's actually pretty simple.  There is an .sln that will build the core libraries.  Some examples and auxiliary projects will fail, but that doesn't matter.

That being said, someone else has recently told me that the repository is broken because the asmjit submodule link is broken.  I have let the author know.  I'm going to close this because it is unrelated to dumpwow, and supporting hadesmem is beyond the scope of this project.

Also just so you're aware I do plan to post binaries after I fix a few things.  I'm currently working on decrypting DLL import thunks and restoring the IAT.

**Comment by namreeb** [comment]
In case you're interested, hadesmem has been rehosted (with permission from the author) here: https://github.com/namreeb/hadesmem -- complete with an action and artifacts.
