### ISSUE TITLE
Failed to find LdrpCallTlsInitializers

### ISSUE THREAD

**Issue by laojunyi123** [namreeb/dumpwow#7]
Using it in win7sp1 returns "Failed to find LdrpCallTlsInitializers" error! I am using the 3.07 binary file. Maybe I should rebuild the entire dumpwow or I am missing something! I also tried to build hadesmem! But CMAKE always prompts me "HADESMEM_ROOT not set." but I did set it! I need your help, can you give me some advice or guidance?

**Comment by laojunyi123** [comment]
Sorry! Wrong! The binary file version is 0.3

**Comment by namreeb** [comment]
This is probably because the pattern used to find `LdrpCallTlsInitializers` is targeted to Windows 10, not Windows 7.  I do not plan to update this to support Windows 7 as it has reached its end of life ([see here](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962#:~:text=The%20specific%20end%20of%20support,longer%20available%20for%20the%20product.)).  If you want to submit a merge request that adds that pattern for Windows 7 I would consider it.

**Comment by laojunyi123** [comment]
Thank you for your help

**Comment by ZaDarkSide** [comment]
This error happens also on Windows 10 x64 Version 1709 build 16299.192.
